name: Lines of Code Badge

on:
  push:
    branches: [ main ]

jobs:
  badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Badge generieren und einfügen
        uses: Xany0/tokei-badge-action@v1.0.1
        with:
          file: "README.md"
